name: OpenEnchants
version: ${project.version}
main: industries.dreadmaw.openenchants.Plugin
version: 0.0.1
api-version: 1.8.8
authors: [ konst-aa ]
description: Custom enchantments framework WIP
website: https://github.com/dreadmaw-industries/open-enchants.git
commands:
  menu:
    description: Open the inventory menu
  customenchant:
    description: Enchant stuff
  customanvil:
    description: Enchanting interface
  enchanter:
    description: Another enchanting interface?